apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: small
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
  annotations: 
    apiconnect-operator/backups-not-configured: "true"
  namespace: apic
spec:
  license:
    accept: true
    license: L-MMBZ-295QZQ
    metric: VIRTUAL_PROCESSOR_CORE
    use: production
  analytics:
    ingestion:
      queue:
        type: persisted
    storage:
      enabled: true
      type: shared
    mtlsValidateClient: true
  portal:
    mtlsValidateClient: true
  profile: n1xc7.m48
  version: 10.0.7.0
  storageClassName: ocs-storagecluster-ceph-rbd