apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ui-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: default
  source:
    path: APIC/resources/platform-ui/instance
    repoURL: https://github.com/eci-cicd/apic-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
